// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file recipe/v1/recipe.proto (package recipe.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetRecipeRequest, GetRecipeResponse} from "./recipe_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service recipe.v1.RecipeService
 */
export const RecipeService = {
  typeName: "recipe.v1.RecipeService",
  methods: {
    /**
     * @generated from rpc recipe.v1.RecipeService.GetRecipe
     */
    getRecipe: {
      name: "GetRecipe",
      I: GetRecipeRequest,
      O: GetRecipeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

