// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file recipe/v1/recipe.proto (package recipev1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetRecipeRequest, GetRecipeResponse} from "./recipe_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service recipev1.RecipeService
 */
export const RecipeService = {
  typeName: "recipev1.RecipeService",
  methods: {
    /**
     * @generated from rpc recipev1.RecipeService.Login
     */
    login: {
      name: "Login",
      I: GetRecipeRequest,
      O: GetRecipeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

