// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file recipe/v1/recipe.proto (package recipe.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message recipe.v1.Recipe
 */
export class Recipe extends Message<Recipe> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  constructor(data?: PartialMessage<Recipe>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.Recipe";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Recipe {
    return new Recipe().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Recipe {
    return new Recipe().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Recipe {
    return new Recipe().fromJsonString(jsonString, options);
  }

  static equals(a: Recipe | PlainMessage<Recipe> | undefined, b: Recipe | PlainMessage<Recipe> | undefined): boolean {
    return proto3.util.equals(Recipe, a, b);
  }
}

/**
 * @generated from message recipe.v1.RecipeStep
 */
export class RecipeStep extends Message<RecipeStep> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: int32 order = 2;
   */
  order = 0;

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  constructor(data?: PartialMessage<RecipeStep>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.RecipeStep";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecipeStep {
    return new RecipeStep().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecipeStep {
    return new RecipeStep().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecipeStep {
    return new RecipeStep().fromJsonString(jsonString, options);
  }

  static equals(a: RecipeStep | PlainMessage<RecipeStep> | undefined, b: RecipeStep | PlainMessage<RecipeStep> | undefined): boolean {
    return proto3.util.equals(RecipeStep, a, b);
  }
}

/**
 * @generated from message recipe.v1.SingleRecipeRequest
 */
export class SingleRecipeRequest extends Message<SingleRecipeRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  constructor(data?: PartialMessage<SingleRecipeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.SingleRecipeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SingleRecipeRequest {
    return new SingleRecipeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SingleRecipeRequest {
    return new SingleRecipeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SingleRecipeRequest {
    return new SingleRecipeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SingleRecipeRequest | PlainMessage<SingleRecipeRequest> | undefined, b: SingleRecipeRequest | PlainMessage<SingleRecipeRequest> | undefined): boolean {
    return proto3.util.equals(SingleRecipeRequest, a, b);
  }
}

/**
 * @generated from message recipe.v1.SingleRecipeResponse
 */
export class SingleRecipeResponse extends Message<SingleRecipeResponse> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: repeated recipe.v1.RecipeStep steps = 3;
   */
  steps: RecipeStep[] = [];

  constructor(data?: PartialMessage<SingleRecipeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.SingleRecipeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "steps", kind: "message", T: RecipeStep, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SingleRecipeResponse {
    return new SingleRecipeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SingleRecipeResponse {
    return new SingleRecipeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SingleRecipeResponse {
    return new SingleRecipeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SingleRecipeResponse | PlainMessage<SingleRecipeResponse> | undefined, b: SingleRecipeResponse | PlainMessage<SingleRecipeResponse> | undefined): boolean {
    return proto3.util.equals(SingleRecipeResponse, a, b);
  }
}

/**
 * @generated from message recipe.v1.AllRecipesRequest
 */
export class AllRecipesRequest extends Message<AllRecipesRequest> {
  /**
   * @generated from field: int32 offset = 1;
   */
  offset = 0;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  /**
   * @generated from field: string search = 3;
   */
  search = "";

  constructor(data?: PartialMessage<AllRecipesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.AllRecipesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllRecipesRequest {
    return new AllRecipesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllRecipesRequest {
    return new AllRecipesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllRecipesRequest {
    return new AllRecipesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AllRecipesRequest | PlainMessage<AllRecipesRequest> | undefined, b: AllRecipesRequest | PlainMessage<AllRecipesRequest> | undefined): boolean {
    return proto3.util.equals(AllRecipesRequest, a, b);
  }
}

/**
 * @generated from message recipe.v1.AllRecipesResponse
 */
export class AllRecipesResponse extends Message<AllRecipesResponse> {
  /**
   * @generated from field: repeated recipe.v1.Recipe recipes = 1;
   */
  recipes: Recipe[] = [];

  constructor(data?: PartialMessage<AllRecipesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.AllRecipesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "recipes", kind: "message", T: Recipe, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllRecipesResponse {
    return new AllRecipesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllRecipesResponse {
    return new AllRecipesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllRecipesResponse {
    return new AllRecipesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AllRecipesResponse | PlainMessage<AllRecipesResponse> | undefined, b: AllRecipesResponse | PlainMessage<AllRecipesResponse> | undefined): boolean {
    return proto3.util.equals(AllRecipesResponse, a, b);
  }
}

/**
 * @generated from message recipe.v1.CreateRecipeRequest
 */
export class CreateRecipeRequest extends Message<CreateRecipeRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: repeated recipe.v1.CreateRecipeRequest.CreateRecipeStep steps = 4;
   */
  steps: CreateRecipeRequest_CreateRecipeStep[] = [];

  constructor(data?: PartialMessage<CreateRecipeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.CreateRecipeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "steps", kind: "message", T: CreateRecipeRequest_CreateRecipeStep, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRecipeRequest {
    return new CreateRecipeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRecipeRequest {
    return new CreateRecipeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRecipeRequest {
    return new CreateRecipeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRecipeRequest | PlainMessage<CreateRecipeRequest> | undefined, b: CreateRecipeRequest | PlainMessage<CreateRecipeRequest> | undefined): boolean {
    return proto3.util.equals(CreateRecipeRequest, a, b);
  }
}

/**
 * @generated from message recipe.v1.CreateRecipeRequest.CreateRecipeStep
 */
export class CreateRecipeRequest_CreateRecipeStep extends Message<CreateRecipeRequest_CreateRecipeStep> {
  /**
   * @generated from field: int32 order = 1;
   */
  order = 0;

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  constructor(data?: PartialMessage<CreateRecipeRequest_CreateRecipeStep>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.CreateRecipeRequest.CreateRecipeStep";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "order", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRecipeRequest_CreateRecipeStep {
    return new CreateRecipeRequest_CreateRecipeStep().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRecipeRequest_CreateRecipeStep {
    return new CreateRecipeRequest_CreateRecipeStep().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRecipeRequest_CreateRecipeStep {
    return new CreateRecipeRequest_CreateRecipeStep().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRecipeRequest_CreateRecipeStep | PlainMessage<CreateRecipeRequest_CreateRecipeStep> | undefined, b: CreateRecipeRequest_CreateRecipeStep | PlainMessage<CreateRecipeRequest_CreateRecipeStep> | undefined): boolean {
    return proto3.util.equals(CreateRecipeRequest_CreateRecipeStep, a, b);
  }
}

/**
 * @generated from message recipe.v1.CreateRecipeResponse
 */
export class CreateRecipeResponse extends Message<CreateRecipeResponse> {
  /**
   * @generated from field: int32 recipe_id = 1;
   */
  recipeId = 0;

  constructor(data?: PartialMessage<CreateRecipeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "recipe.v1.CreateRecipeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "recipe_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRecipeResponse {
    return new CreateRecipeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRecipeResponse {
    return new CreateRecipeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRecipeResponse {
    return new CreateRecipeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRecipeResponse | PlainMessage<CreateRecipeResponse> | undefined, b: CreateRecipeResponse | PlainMessage<CreateRecipeResponse> | undefined): boolean {
    return proto3.util.equals(CreateRecipeResponse, a, b);
  }
}

