// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file recipe/v1/recipe.proto (package recipe.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AllRecipesRequest, AllRecipesResponse, CreateRecipeRequest, CreateRecipeResponse, SingleRecipeRequest, SingleRecipeResponse } from "./recipe_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service recipe.v1.RecipeService
 */
export const RecipeService = {
  typeName: "recipe.v1.RecipeService",
  methods: {
    /**
     * @generated from rpc recipe.v1.RecipeService.SingleRecipe
     */
    singleRecipe: {
      name: "SingleRecipe",
      I: SingleRecipeRequest,
      O: SingleRecipeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc recipe.v1.RecipeService.AllRecipes
     */
    allRecipes: {
      name: "AllRecipes",
      I: AllRecipesRequest,
      O: AllRecipesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc recipe.v1.RecipeService.CreateRecipe
     */
    createRecipe: {
      name: "CreateRecipe",
      I: CreateRecipeRequest,
      O: CreateRecipeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

