// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"
)

type Recipe struct {
	ID              int64
	Name            string
	ContentMarkdown string
	CreatedAt       time.Time
}
