// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ingredient/v1/ingredient.proto

package ingredientv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gluttony/internal/proto/ingredient/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngredientServiceName is the fully-qualified name of the IngredientService service.
	IngredientServiceName = "ingredient.v1.IngredientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngredientServiceAllProcedure is the fully-qualified name of the IngredientService's All RPC.
	IngredientServiceAllProcedure = "/ingredient.v1.IngredientService/All"
	// IngredientServiceCreateProcedure is the fully-qualified name of the IngredientService's Create
	// RPC.
	IngredientServiceCreateProcedure = "/ingredient.v1.IngredientService/Create"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	ingredientServiceServiceDescriptor      = v1.File_ingredient_v1_ingredient_proto.Services().ByName("IngredientService")
	ingredientServiceAllMethodDescriptor    = ingredientServiceServiceDescriptor.Methods().ByName("All")
	ingredientServiceCreateMethodDescriptor = ingredientServiceServiceDescriptor.Methods().ByName("Create")
)

// IngredientServiceClient is a client for the ingredient.v1.IngredientService service.
type IngredientServiceClient interface {
	All(context.Context, *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllResponse], error)
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
}

// NewIngredientServiceClient constructs a client for the ingredient.v1.IngredientService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngredientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngredientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &ingredientServiceClient{
		all: connect.NewClient[v1.AllRequest, v1.AllResponse](
			httpClient,
			baseURL+IngredientServiceAllProcedure,
			connect.WithSchema(ingredientServiceAllMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+IngredientServiceCreateProcedure,
			connect.WithSchema(ingredientServiceCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingredientServiceClient implements IngredientServiceClient.
type ingredientServiceClient struct {
	all    *connect.Client[v1.AllRequest, v1.AllResponse]
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
}

// All calls ingredient.v1.IngredientService.All.
func (c *ingredientServiceClient) All(ctx context.Context, req *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllResponse], error) {
	return c.all.CallUnary(ctx, req)
}

// Create calls ingredient.v1.IngredientService.Create.
func (c *ingredientServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// IngredientServiceHandler is an implementation of the ingredient.v1.IngredientService service.
type IngredientServiceHandler interface {
	All(context.Context, *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllResponse], error)
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
}

// NewIngredientServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngredientServiceHandler(svc IngredientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingredientServiceAllHandler := connect.NewUnaryHandler(
		IngredientServiceAllProcedure,
		svc.All,
		connect.WithSchema(ingredientServiceAllMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ingredientServiceCreateHandler := connect.NewUnaryHandler(
		IngredientServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(ingredientServiceCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/ingredient.v1.IngredientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngredientServiceAllProcedure:
			ingredientServiceAllHandler.ServeHTTP(w, r)
		case IngredientServiceCreateProcedure:
			ingredientServiceCreateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngredientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIngredientServiceHandler struct{}

func (UnimplementedIngredientServiceHandler) All(context.Context, *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ingredient.v1.IngredientService.All is not implemented"))
}

func (UnimplementedIngredientServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ingredient.v1.IngredientService.Create is not implemented"))
}
