// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ingredient/v1/ingredient.proto

package ingredientv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gluttony/internal/proto/ingredient/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RecipeServiceName is the fully-qualified name of the RecipeService service.
	RecipeServiceName = "ingredient.v1.RecipeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RecipeServiceAllProcedure is the fully-qualified name of the RecipeService's All RPC.
	RecipeServiceAllProcedure = "/ingredient.v1.RecipeService/All"
	// RecipeServiceCreateProcedure is the fully-qualified name of the RecipeService's Create RPC.
	RecipeServiceCreateProcedure = "/ingredient.v1.RecipeService/Create"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	recipeServiceServiceDescriptor      = v1.File_ingredient_v1_ingredient_proto.Services().ByName("RecipeService")
	recipeServiceAllMethodDescriptor    = recipeServiceServiceDescriptor.Methods().ByName("All")
	recipeServiceCreateMethodDescriptor = recipeServiceServiceDescriptor.Methods().ByName("Create")
)

// RecipeServiceClient is a client for the ingredient.v1.RecipeService service.
type RecipeServiceClient interface {
	All(context.Context, *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllRequest], error)
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
}

// NewRecipeServiceClient constructs a client for the ingredient.v1.RecipeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRecipeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RecipeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &recipeServiceClient{
		all: connect.NewClient[v1.AllRequest, v1.AllRequest](
			httpClient,
			baseURL+RecipeServiceAllProcedure,
			connect.WithSchema(recipeServiceAllMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+RecipeServiceCreateProcedure,
			connect.WithSchema(recipeServiceCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// recipeServiceClient implements RecipeServiceClient.
type recipeServiceClient struct {
	all    *connect.Client[v1.AllRequest, v1.AllRequest]
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
}

// All calls ingredient.v1.RecipeService.All.
func (c *recipeServiceClient) All(ctx context.Context, req *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllRequest], error) {
	return c.all.CallUnary(ctx, req)
}

// Create calls ingredient.v1.RecipeService.Create.
func (c *recipeServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// RecipeServiceHandler is an implementation of the ingredient.v1.RecipeService service.
type RecipeServiceHandler interface {
	All(context.Context, *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllRequest], error)
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
}

// NewRecipeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRecipeServiceHandler(svc RecipeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	recipeServiceAllHandler := connect.NewUnaryHandler(
		RecipeServiceAllProcedure,
		svc.All,
		connect.WithSchema(recipeServiceAllMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	recipeServiceCreateHandler := connect.NewUnaryHandler(
		RecipeServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(recipeServiceCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/ingredient.v1.RecipeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RecipeServiceAllProcedure:
			recipeServiceAllHandler.ServeHTTP(w, r)
		case RecipeServiceCreateProcedure:
			recipeServiceCreateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRecipeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRecipeServiceHandler struct{}

func (UnimplementedRecipeServiceHandler) All(context.Context, *connect.Request[v1.AllRequest]) (*connect.Response[v1.AllRequest], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ingredient.v1.RecipeService.All is not implemented"))
}

func (UnimplementedRecipeServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ingredient.v1.RecipeService.Create is not implemented"))
}
