/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesRecipeIdImport } from './routes/recipes/$recipeId'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const RecipesIndexLazyImport = createFileRoute('/recipes/')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexLazyRoute = RecipesIndexLazyImport.update({
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/recipes/index.lazy').then((d) => d.Route))

const RecipesRecipeIdRoute = RecipesRecipeIdImport.update({
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/recipes/$recipeId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$recipeId': {
      preLoaderRoute: typeof RecipesRecipeIdImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      preLoaderRoute: typeof RecipesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginLazyRoute,
  RecipesRecipeIdRoute,
  RecipesIndexLazyRoute,
])

/* prettier-ignore-end */
