// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file user/v1/user.proto (package userv1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {LoginRequest, LoginResponse} from "./user_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service userv1.UserService
 */
export const UserService = {
  typeName: "userv1.UserService",
  methods: {
    /**
     * @generated from rpc userv1.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

