// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: recipe/v1/recipe.proto

package recipev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gluttony/internal/proto/recipe/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RecipeServiceName is the fully-qualified name of the RecipeService service.
	RecipeServiceName = "recipe.v1.RecipeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RecipeServiceSingleRecipeProcedure is the fully-qualified name of the RecipeService's
	// SingleRecipe RPC.
	RecipeServiceSingleRecipeProcedure = "/recipe.v1.RecipeService/SingleRecipe"
	// RecipeServiceAllRecipesProcedure is the fully-qualified name of the RecipeService's AllRecipes
	// RPC.
	RecipeServiceAllRecipesProcedure = "/recipe.v1.RecipeService/AllRecipes"
	// RecipeServiceCreateRecipeProcedure is the fully-qualified name of the RecipeService's
	// CreateRecipe RPC.
	RecipeServiceCreateRecipeProcedure = "/recipe.v1.RecipeService/CreateRecipe"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	recipeServiceServiceDescriptor            = v1.File_recipe_v1_recipe_proto.Services().ByName("RecipeService")
	recipeServiceSingleRecipeMethodDescriptor = recipeServiceServiceDescriptor.Methods().ByName("SingleRecipe")
	recipeServiceAllRecipesMethodDescriptor   = recipeServiceServiceDescriptor.Methods().ByName("AllRecipes")
	recipeServiceCreateRecipeMethodDescriptor = recipeServiceServiceDescriptor.Methods().ByName("CreateRecipe")
)

// RecipeServiceClient is a client for the recipe.v1.RecipeService service.
type RecipeServiceClient interface {
	SingleRecipe(context.Context, *connect.Request[v1.SingleRecipeRequest]) (*connect.Response[v1.SingleRecipeResponse], error)
	AllRecipes(context.Context, *connect.Request[v1.AllRecipesRequest]) (*connect.Response[v1.AllRecipesResponse], error)
	CreateRecipe(context.Context, *connect.Request[v1.CreateRecipeRequest]) (*connect.Response[v1.CreateRecipeResponse], error)
}

// NewRecipeServiceClient constructs a client for the recipe.v1.RecipeService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRecipeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RecipeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &recipeServiceClient{
		singleRecipe: connect.NewClient[v1.SingleRecipeRequest, v1.SingleRecipeResponse](
			httpClient,
			baseURL+RecipeServiceSingleRecipeProcedure,
			connect.WithSchema(recipeServiceSingleRecipeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		allRecipes: connect.NewClient[v1.AllRecipesRequest, v1.AllRecipesResponse](
			httpClient,
			baseURL+RecipeServiceAllRecipesProcedure,
			connect.WithSchema(recipeServiceAllRecipesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createRecipe: connect.NewClient[v1.CreateRecipeRequest, v1.CreateRecipeResponse](
			httpClient,
			baseURL+RecipeServiceCreateRecipeProcedure,
			connect.WithSchema(recipeServiceCreateRecipeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// recipeServiceClient implements RecipeServiceClient.
type recipeServiceClient struct {
	singleRecipe *connect.Client[v1.SingleRecipeRequest, v1.SingleRecipeResponse]
	allRecipes   *connect.Client[v1.AllRecipesRequest, v1.AllRecipesResponse]
	createRecipe *connect.Client[v1.CreateRecipeRequest, v1.CreateRecipeResponse]
}

// SingleRecipe calls recipe.v1.RecipeService.SingleRecipe.
func (c *recipeServiceClient) SingleRecipe(ctx context.Context, req *connect.Request[v1.SingleRecipeRequest]) (*connect.Response[v1.SingleRecipeResponse], error) {
	return c.singleRecipe.CallUnary(ctx, req)
}

// AllRecipes calls recipe.v1.RecipeService.AllRecipes.
func (c *recipeServiceClient) AllRecipes(ctx context.Context, req *connect.Request[v1.AllRecipesRequest]) (*connect.Response[v1.AllRecipesResponse], error) {
	return c.allRecipes.CallUnary(ctx, req)
}

// CreateRecipe calls recipe.v1.RecipeService.CreateRecipe.
func (c *recipeServiceClient) CreateRecipe(ctx context.Context, req *connect.Request[v1.CreateRecipeRequest]) (*connect.Response[v1.CreateRecipeResponse], error) {
	return c.createRecipe.CallUnary(ctx, req)
}

// RecipeServiceHandler is an implementation of the recipe.v1.RecipeService service.
type RecipeServiceHandler interface {
	SingleRecipe(context.Context, *connect.Request[v1.SingleRecipeRequest]) (*connect.Response[v1.SingleRecipeResponse], error)
	AllRecipes(context.Context, *connect.Request[v1.AllRecipesRequest]) (*connect.Response[v1.AllRecipesResponse], error)
	CreateRecipe(context.Context, *connect.Request[v1.CreateRecipeRequest]) (*connect.Response[v1.CreateRecipeResponse], error)
}

// NewRecipeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRecipeServiceHandler(svc RecipeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	recipeServiceSingleRecipeHandler := connect.NewUnaryHandler(
		RecipeServiceSingleRecipeProcedure,
		svc.SingleRecipe,
		connect.WithSchema(recipeServiceSingleRecipeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	recipeServiceAllRecipesHandler := connect.NewUnaryHandler(
		RecipeServiceAllRecipesProcedure,
		svc.AllRecipes,
		connect.WithSchema(recipeServiceAllRecipesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	recipeServiceCreateRecipeHandler := connect.NewUnaryHandler(
		RecipeServiceCreateRecipeProcedure,
		svc.CreateRecipe,
		connect.WithSchema(recipeServiceCreateRecipeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/recipe.v1.RecipeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RecipeServiceSingleRecipeProcedure:
			recipeServiceSingleRecipeHandler.ServeHTTP(w, r)
		case RecipeServiceAllRecipesProcedure:
			recipeServiceAllRecipesHandler.ServeHTTP(w, r)
		case RecipeServiceCreateRecipeProcedure:
			recipeServiceCreateRecipeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRecipeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRecipeServiceHandler struct{}

func (UnimplementedRecipeServiceHandler) SingleRecipe(context.Context, *connect.Request[v1.SingleRecipeRequest]) (*connect.Response[v1.SingleRecipeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("recipe.v1.RecipeService.SingleRecipe is not implemented"))
}

func (UnimplementedRecipeServiceHandler) AllRecipes(context.Context, *connect.Request[v1.AllRecipesRequest]) (*connect.Response[v1.AllRecipesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("recipe.v1.RecipeService.AllRecipes is not implemented"))
}

func (UnimplementedRecipeServiceHandler) CreateRecipe(context.Context, *connect.Request[v1.CreateRecipeRequest]) (*connect.Response[v1.CreateRecipeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("recipe.v1.RecipeService.CreateRecipe is not implemented"))
}
