// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"
)

const allIngredients = `-- name: AllIngredients :many
SELECT id, (name ->> $1::text)::text as name
FROM ingredients
WHERE CASE
          WHEN $2 != '' THEN to_tsvector(name ->> $1::text) @@
                                             websearch_to_tsquery($2)
          ELSE TRUE END
  AND (name ->> $1::text)::text IS NOT NULL
OFFSET $3 ROWS FETCH FIRST $4 ROW ONLY
`

type AllIngredientsParams struct {
	Locale string
	Search interface{}
	Offset int32
	Limit  int32
}

type AllIngredientsRow struct {
	ID   int32
	Name string
}

func (q *Queries) AllIngredients(ctx context.Context, arg AllIngredientsParams) ([]AllIngredientsRow, error) {
	rows, err := q.db.Query(ctx, allIngredients,
		arg.Locale,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllIngredientsRow
	for rows.Next() {
		var i AllIngredientsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIngredient = `-- name: CreateIngredient :exec
INSERT INTO ingredients (name)
values ($1)
`

func (q *Queries) CreateIngredient(ctx context.Context, name []byte) error {
	_, err := q.db.Exec(ctx, createIngredient, name)
	return err
}
