// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allIngredients = `-- name: AllIngredients :many
SELECT ingredients.id,
       (ingredients.name ->> $1::text)::text as name
FROM ingredients,
     to_tsvector($2, ingredients.name ->> $1::text) document,
     websearch_to_tsquery($2, $3) query,
     similarity($3, ingredients.name ->> $1::text) similarity,
     NULLIF(ts_rank(document, query), 0)                  rank_name
WHERE ingredients.name ->> $1 IS NOT NULL
  AND CASE
          WHEN $3 != '' THEN (query @@ document OR similarity > 0.5)
          ELSE TRUE END
ORDER BY rank_name, similarity DESC NULLS LAST
OFFSET $4 ROWS FETCH FIRST $5 ROW ONLY
`

type AllIngredientsParams struct {
	Locale       string
	SearchLocale interface{}
	Search       string
	Offset       int64
	Limit        int64
}

type AllIngredientsRow struct {
	ID   int32
	Name pgtype.Text
}

func (q *Queries) AllIngredients(ctx context.Context, arg AllIngredientsParams) ([]AllIngredientsRow, error) {
	rows, err := q.db.Query(ctx, allIngredients,
		arg.Locale,
		arg.SearchLocale,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllIngredientsRow
	for rows.Next() {
		var i AllIngredientsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIngredient = `-- name: CreateIngredient :exec
INSERT INTO ingredients (name)
values ($1)
`

func (q *Queries) CreateIngredient(ctx context.Context, name []byte) error {
	_, err := q.db.Exec(ctx, createIngredient, name)
	return err
}
