// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file share/v1/share.proto (package share.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { AllRecipesRequest } from "../../recipe/v1/recipe_pb.js";

/**
 * @generated from message share.v1.ok
 */
export class ok extends Message<ok> {
  /**
   * @generated from field: recipe.v1.AllRecipesRequest ok = 1;
   */
  ok?: AllRecipesRequest;

  constructor(data?: PartialMessage<ok>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "share.v1.ok";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "message", T: AllRecipesRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ok {
    return new ok().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ok {
    return new ok().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ok {
    return new ok().fromJsonString(jsonString, options);
  }

  static equals(a: ok | PlainMessage<ok> | undefined, b: ok | PlainMessage<ok> | undefined): boolean {
    return proto3.util.equals(ok, a, b);
  }
}

