// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file ingredient/v1/ingredient.proto (package ingredient.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AllRequest, AllResponse, CreateRequest, CreateResponse, SingleRequest, SingleResponse } from "./ingredient_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ingredient.v1.IngredientService
 */
export const IngredientService = {
  typeName: "ingredient.v1.IngredientService",
  methods: {
    /**
     * @generated from rpc ingredient.v1.IngredientService.All
     */
    all: {
      name: "All",
      I: AllRequest,
      O: AllResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ingredient.v1.IngredientService.Single
     */
    single: {
      name: "Single",
      I: SingleRequest,
      O: SingleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ingredient.v1.IngredientService.Create
     */
    create: {
      name: "Create",
      I: CreateRequest,
      O: CreateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

