// @generated by protoc-gen-es v1.8.0 with parameter "target=ts"
// @generated from file ingredient/v1/ingredient.proto (package ingredient.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum ingredient.v1.Unit
 */
export enum Unit {
  /**
   * @generated from enum value: UNIT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: UNIT_WEIGHT = 1;
   */
  WEIGHT = 1,

  /**
   * @generated from enum value: UNIT_VOLUME = 2;
   */
  VOLUME = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Unit)
proto3.util.setEnumType(Unit, "ingredient.v1.Unit", [
  { no: 0, name: "UNIT_UNSPECIFIED" },
  { no: 1, name: "UNIT_WEIGHT" },
  { no: 2, name: "UNIT_VOLUME" },
]);

/**
 * @generated from message ingredient.v1.Ingredient
 */
export class Ingredient extends Message<Ingredient> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: ingredient.v1.Unit unit = 3;
   */
  unit = Unit.UNSPECIFIED;

  constructor(data?: PartialMessage<Ingredient>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.Ingredient";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "unit", kind: "enum", T: proto3.getEnumType(Unit) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Ingredient {
    return new Ingredient().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Ingredient {
    return new Ingredient().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Ingredient {
    return new Ingredient().fromJsonString(jsonString, options);
  }

  static equals(a: Ingredient | PlainMessage<Ingredient> | undefined, b: Ingredient | PlainMessage<Ingredient> | undefined): boolean {
    return proto3.util.equals(Ingredient, a, b);
  }
}

/**
 * @generated from message ingredient.v1.AllRequest
 */
export class AllRequest extends Message<AllRequest> {
  /**
   * @generated from field: int32 offset = 1;
   */
  offset = 0;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  /**
   * @generated from field: string search = 3;
   */
  search = "";

  constructor(data?: PartialMessage<AllRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.AllRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllRequest {
    return new AllRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllRequest {
    return new AllRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllRequest {
    return new AllRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AllRequest | PlainMessage<AllRequest> | undefined, b: AllRequest | PlainMessage<AllRequest> | undefined): boolean {
    return proto3.util.equals(AllRequest, a, b);
  }
}

/**
 * @generated from message ingredient.v1.AllResponse
 */
export class AllResponse extends Message<AllResponse> {
  /**
   * @generated from field: repeated ingredient.v1.Ingredient ingredients = 1;
   */
  ingredients: Ingredient[] = [];

  constructor(data?: PartialMessage<AllResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.AllResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ingredients", kind: "message", T: Ingredient, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllResponse {
    return new AllResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllResponse {
    return new AllResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllResponse {
    return new AllResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AllResponse | PlainMessage<AllResponse> | undefined, b: AllResponse | PlainMessage<AllResponse> | undefined): boolean {
    return proto3.util.equals(AllResponse, a, b);
  }
}

/**
 * @generated from message ingredient.v1.CreateRequest
 */
export class CreateRequest extends Message<CreateRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string locale = 2;
   */
  locale = "";

  /**
   * @generated from field: ingredient.v1.Unit unit = 3;
   */
  unit = Unit.UNSPECIFIED;

  constructor(data?: PartialMessage<CreateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.CreateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "locale", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "unit", kind: "enum", T: proto3.getEnumType(Unit) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRequest {
    return new CreateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRequest {
    return new CreateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRequest {
    return new CreateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRequest | PlainMessage<CreateRequest> | undefined, b: CreateRequest | PlainMessage<CreateRequest> | undefined): boolean {
    return proto3.util.equals(CreateRequest, a, b);
  }
}

/**
 * @generated from message ingredient.v1.CreateResponse
 */
export class CreateResponse extends Message<CreateResponse> {
  constructor(data?: PartialMessage<CreateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.CreateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateResponse {
    return new CreateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateResponse {
    return new CreateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateResponse {
    return new CreateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateResponse | PlainMessage<CreateResponse> | undefined, b: CreateResponse | PlainMessage<CreateResponse> | undefined): boolean {
    return proto3.util.equals(CreateResponse, a, b);
  }
}

/**
 * @generated from message ingredient.v1.SingleRequest
 */
export class SingleRequest extends Message<SingleRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  constructor(data?: PartialMessage<SingleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.SingleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SingleRequest {
    return new SingleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SingleRequest {
    return new SingleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SingleRequest {
    return new SingleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SingleRequest | PlainMessage<SingleRequest> | undefined, b: SingleRequest | PlainMessage<SingleRequest> | undefined): boolean {
    return proto3.util.equals(SingleRequest, a, b);
  }
}

/**
 * @generated from message ingredient.v1.SingleResponse
 */
export class SingleResponse extends Message<SingleResponse> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: ingredient.v1.Unit unit = 3;
   */
  unit = Unit.UNSPECIFIED;

  constructor(data?: PartialMessage<SingleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ingredient.v1.SingleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "unit", kind: "enum", T: proto3.getEnumType(Unit) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SingleResponse {
    return new SingleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SingleResponse {
    return new SingleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SingleResponse {
    return new SingleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SingleResponse | PlainMessage<SingleResponse> | undefined, b: SingleResponse | PlainMessage<SingleResponse> | undefined): boolean {
    return proto3.util.equals(SingleResponse, a, b);
  }
}

