// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package postgresql

import (
	"context"
)

// iteratorForCreateRecipeSteps implements pgx.CopyFromSource.
type iteratorForCreateRecipeSteps struct {
	rows                 []CreateRecipeStepsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRecipeSteps) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRecipeSteps) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RecipeID,
		r.rows[0].Description,
		r.rows[0].Order,
	}, nil
}

func (r iteratorForCreateRecipeSteps) Err() error {
	return nil
}

func (q *Queries) CreateRecipeSteps(ctx context.Context, arg []CreateRecipeStepsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recipe_steps"}, []string{"recipe_id", "description", "order"}, &iteratorForCreateRecipeSteps{rows: arg})
}
