// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package postgresql

import (
	"context"
)

// iteratorForCreateRecipeIngredientEdges implements pgx.CopyFromSource.
type iteratorForCreateRecipeIngredientEdges struct {
	rows                 []CreateRecipeIngredientEdgesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRecipeIngredientEdges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRecipeIngredientEdges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RecipeID,
		r.rows[0].IngredientID,
	}, nil
}

func (r iteratorForCreateRecipeIngredientEdges) Err() error {
	return nil
}

func (q *Queries) CreateRecipeIngredientEdges(ctx context.Context, arg []CreateRecipeIngredientEdgesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recipes_ingredients"}, []string{"recipe_id", "ingredient_id"}, &iteratorForCreateRecipeIngredientEdges{rows: arg})
}
