// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"
)

const allRecipes = `-- name: AllRecipes :many
SELECT id, (name ->> $1)::text as name, (description ->> $1)::text as description
FROM recipes as rank
WHERE CASE
          WHEN $2 != '' THEN to_tsvector(name->>$1::text) @@ websearch_to_tsquery($2)
          ELSE TRUE END
OFFSET $3 ROWS FETCH FIRST $4 ROW ONLY
`

type AllRecipesParams struct {
	Locale []byte
	Search interface{}
	Offset int32
	Limit  int32
}

type AllRecipesRow struct {
	ID          int32
	Name        string
	Description string
}

func (q *Queries) AllRecipes(ctx context.Context, arg AllRecipesParams) ([]AllRecipesRow, error) {
	rows, err := q.db.Query(ctx, allRecipes,
		arg.Locale,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllRecipesRow
	for rows.Next() {
		var i AllRecipesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (name, description, content)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateRecipeParams struct {
	Name        []byte
	Description []byte
	Content     []byte
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.Name, arg.Description, arg.Content)
	var id int32
	err := row.Scan(&id)
	return id, err
}

type CreateRecipeIngredientEdgesParams struct {
	RecipeID     int32
	IngredientID int32
}

const singleRecipe = `-- name: SingleRecipe :one
SELECT id,
       (name ->> $1::text)::text as name,
       (description ->> $1::text)::text as description,
       (content ->> $1::text)::text    as content
FROM recipes
WHERE recipes.id = $2
`

type SingleRecipeParams struct {
	Locale   string
	RecipeID int32
}

type SingleRecipeRow struct {
	ID          int32
	Name        string
	Description string
	Content     string
}

func (q *Queries) SingleRecipe(ctx context.Context, arg SingleRecipeParams) (SingleRecipeRow, error) {
	row := q.db.QueryRow(ctx, singleRecipe, arg.Locale, arg.RecipeID)
	var i SingleRecipeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
	)
	return i, err
}
