// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

type Recipe struct {
	ID          int32
	Name        string
	Description string
}

type RecipeStep struct {
	ID          int32
	RecipeID    int32
	Description string
	Order       int32
}

type User struct {
	ID       int32
	Name     string
	Password string
}
